// packages/taro-demo-vue3/src/pages/basic/navbar.vue
<template>
  <biz-page title="NavBar 头部导航">
    <nut-button :block="true" type="primary" @click="show = true">Hello world!</nut-button>
    <nut-popup v-model:visible="show" :style="{ padding: '30px' }">
      <text>正文</text>
    </nut-popup>
  </biz-page>
</template>

<script setup lang="ts">
const show = ref(false);
</script>

<style scoped lang="scss"></style>

// packages/taro-demo-react/src/pages/basic/navbar.tsx
import { Text } from '@tarojs/components';
import { useState } from 'react';
import { Button, Popup } from '@nutui/nutui-react-taro';
import { BizPage } from '@/components';

export default function Page() {
  const [show, setShow] = useState(false);
  return (
    <BizPage title="NavBar 头部导航">
      <Button block type="primary" onClick={() => setShow(true)}>
        Hello world!
      </Button>
      <Popup visible={show} onClose={() => setShow(false)} style={{ padding: '30px' }}>
        <Text>正文</Text>
      </Popup>
    </BizPage>
  );
}
